version: "3.8"

services:
  postgres:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_DB: "mydb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "oistgres"
    networks:
      - app_network
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - app_network
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/mydb?schema=public"
    networks:
      - app_network
    ports:
      - "8000:8000"
    depends_on:
      - postgres

networks:
  app_network:
    external: true

volumes:
  postgres:
